FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dbt-core==1.8.2 \
    dbt-postgres==1.8.2 \
    psycopg2-binary==2.9.9

WORKDIR /dbt
CMD ["tail", "-f", "/dev/null"]
