FROM python:3.11-slim

RUN pip install --no-cache-dir \
    streamlit==1.35.0 \
    psycopg2-binary==2.9.9 \
    pandas==2.2.2 \
    plotly==5.22.0 \
    sqlalchemy==2.0.30

WORKDIR /app
EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
